"""Initial migration

Revision ID: 27f245f43fb7
Revises: 
Create Date: 2024-05-07 16:50:53.810110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f245f43fb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('failed_login_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('mfa_secret', sa.String(length=100), nullable=True),
    sa.Column('mfa_secret_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
